<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/04/23 12:11:37
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 5,
));
