<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_affiliate' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/03/14 18:20:21
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetAffiliate extends BaseJobeetAffiliate {

	/**
	 * Initializes internal state of JobeetAffiliate object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
	 public function __toString()
	  {
		return sprintf('%s at %s (%s)', $this->getPosition(), $this->getCompany(), $this->getLocation());
	  }
} // JobeetAffiliate
