<?php


/**
 * Skeleton subclass for representing a row from the 'jobeet_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/03/14 18:20:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class JobeetCategory extends BaseJobeetCategory {
	
	/*public function getActiveJobs($max = 10)
	{
	  $criteria = new Criteria();
	  $criteria->add(JobeetJobPeer::CATEGORY_ID, $this->getId());
	  $criteria->setLimit(sfConfig::get('app_max_jobs_on_homepage'));
	  
	  return JobeetJobPeer::getActiveJobs($criteria);
	}*/
	/*public function countActiveJobs()
		{
		  $criteria = new Criteria();
		  $criteria->add(JobeetJobPeer::CATEGORY_ID, $this->getId());
		 
		  return JobeetJobPeer::countActiveJobs($criteria);
		}*/
	
/*	public function getSlug()
		{
		  return Jobeet::slugify($this->getName());
		}*/
		
		public function setName($name)
		{
		  parent::setName($name);
		 
		  $this->setSlug(Jobeet::slugify($name));
		}
		
	public function __toString()
	  {
		return $this->getName();
	  }
	  public function getActiveJobsCriteria()
		{
		  $criteria = new Criteria();
		  $criteria->add(JobeetJobPeer::CATEGORY_ID, $this->getId());
		 
		  return JobeetJobPeer::addActiveJobsCriteria($criteria);
		}
		
		public function getActiveJobs($max = 10)
		{
		  $criteria = $this->getActiveJobsCriteria();
		  $criteria->setLimit($max);
		 
		  return JobeetJobPeer::doSelect($criteria);
		}
		 
		public function countActiveJobs()
		{
		  $criteria = $this->getActiveJobsCriteria();
		 
		  return JobeetJobPeer::doCount($criteria);
		}

} // JobeetCategory
